// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY
import {
  createWorkerAdapter,
  EndpointContext,
  createFakeExpressApp,
} from 'taon/src';

import startFn from '../../../../../../tmp-source-esm-dist/app';
import { GlobalStorage, UtilsSecretEnv } from 'tnp-core/src';
const app = createFakeExpressApp();

export default {
  fetch: createWorkerAdapter(app, async (overrideHost, req, res, env) => {
    const TAON_LOCAL_DEV = env.TAON_LOCAL_DEV === 'true';
    console.log({
      TAON_LOCAL_DEV,
    });
    GlobalStorage.set('TAON_LOCAL_DEV', TAON_LOCAL_DEV);
    GlobalStorage.set(
      UtilsSecretEnv.MASTER_PASS_KEY,
      env[UtilsSecretEnv.MASTER_PASS_KEY],
    );

    // console.log('REQUEST DONE!')
    // console.log({ overrideHost });
    // console.log({ env });
    await startFn({
      overrideExpressApp: app,
      overrideHost,
      cloudflareEnv: env,
    });
    // @ts-ignore
    var ContextsEndpointStorageInstance = // @ts-ignore
      globalThis['$$$ContextsEndpointStorage$$$'];

    const endpoints: EndpointContext[] =
      ContextsEndpointStorageInstance.arr || [];

    await Promise.all(
      endpoints.map(c =>
        c.initControllersHook(ContextsEndpointStorageInstance),
      ),
    );
    console.log(ContextsEndpointStorageInstance.SPECIAL_APP_READY_MESSAGE);
  }),
};
// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY