// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY
import {
  createWorkerAdapter,
  EndpointContext,
  createFakeExpressApp,
} from 'taon/src';

import startFn from '../../../../../../tmp-source-esm-dist/app';
const app = createFakeExpressApp();

export default {
  fetch: createWorkerAdapter(app, async (overrideHost, req, res, env) => {
    // console.log({ overrideHost });
    // console.log({ env });
    await startFn({
      overrideExpressApp: app,
      overrideHost,
      cloudflareEnv: env,
    });
    // @ts-ignore
    var ContextsEndpointStorageInstance = // @ts-ignore
      globalThis['$$$ContextsEndpointStorage$$$'];

    const endpoints: EndpointContext[] =
      ContextsEndpointStorageInstance.arr || [];

    await Promise.all(
      endpoints.map(c =>
        c.initControllersHook(ContextsEndpointStorageInstance),
      ),
    );
    console.log(ContextsEndpointStorageInstance.SPECIAL_APP_READY_MESSAGE);
  }),
};
// THIS FILE IS GENERATED BYT TAON - DO NOT MODIFY
